#  _    _ _   _           _                      _             _  
# | | _(_) |_| |_ _   _  | |_ ___ _ __ _ __ ___ (_)_ __   __ _| | 
# | |/ / | __| __| | | | | __/ _ \ '__| '_ ` _ \| | '_ \ / _` | | 
# |   <| | |_| |_| |_| | | ||  __/ |  | | | | | | | | | | (_| | | 
# |_|\_\_|\__|\__|\__, |  \__\___|_|  |_| |_| |_|_|_| |_|\__,_|_| 
#                 |___/              _          _   _             
#   ___ _   _ ___| |_ ___  _ __ ___ (_)______ _| |_(_) ___  _ __  
#  / __| | | / __| __/ _ \| '_ ` _ \| |_  / _` | __| |/ _ \| '_ \ 
# | (__| |_| \__ \ || (_) | | | | | | |/ / (_| | |_| | (_) | | | |
#  \___|\__,_|___/\__\___/|_| |_| |_|_/___\__,_|\__|_|\___/|_| |_|

##########################################################################

# themes
include Ayu.conf

# terminal opacity and blur
background_opacity 1.0
background_blur 1

# window padding
window_padding_width 10

# advance 
term xterm-kitty

# terminal bell
enable_audio_bell no

# os specific tweaks (Gnome window decoration for wayland)
linux_display_server x11

# font
font_family        JetBrainsMono Nerd Font
bold_font          auto
italic_font        auto
bold_italic_font   auto
font_size 12.0
